version: '3'
services:
  redis:
    image: redis
    volumes:
      - ./data/redis-data:/data
  discordbot:
    build: './discordbot'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./discordbot:/usr/src/app

